name: CI for Angular App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.10.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: false      # Skip fetching submodules
          fetch-depth: 1         # Only fetch the latest commit

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test -- --watch=false --no-progress --browsers=ChromeHeadless

      - name: Build the Angular app into the docs folder
        run: npm run build -- --output-path=docs --base-href=/CIP-CI-CD/

      # Deployment step: Deploy to GitHub Pages from the docs folder
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
